// Auth
export const SET_AUTH_USER = 'SET_AUTH_USER'

// User
export const FETCH_USER_ASYNC = 'FETCH_USER_ASYNC'
export const SIGN_OUT_USER = 'SIGN_OUT_USER'

export const SET_USER = 'SET_USER'
export const SET_USER_PREFERRED_THEME = 'SET_USER_PREFERRED_THEME'

// Themeing and display
export const SET_THEME = 'SET_THEME';
export const TOGGLE_DISPLAY_MODE = 'TOGGLE_DISPLAY_MODE';

// Editor
export const EDITOR_SET_ACTIVE_DOCUMENT_VALUE = 'EDITOR_SET_ACTIVE_DOCUMENT_VALUE';

export const EDITOR_SET_SHORTCUT_TARGET = 'EDITOR_SET_SHORTCUT_TARGET';
export const EDITOR_SET_SHORTCUT_SEARCH = 'EDITOR_SET_SHORTCUT_SEARCH';
export const EDITOR_SET_SHORTCUT_DROP_DOWN_INDEX = 'EDITOR_SET_SHORTCUT_DROP_DOWN_INDEX';

// Defaults from example
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const SET_FILTER = 'SET_FILTER';
